type ROOM_STATUS_PRE_STORAGE = "prestorage";
type ROOM_STATUS_POST_STORAGE = "poststorage";
type ROOM_STATUS_BUILDUP = "buildup";



type ROOM_STATUS = ROOM_STATUS_PRE_STORAGE | ROOM_STATUS_POST_STORAGE | ROOM_STATUS_BUILDUP;